### ISSUE TITLE
Prise en charge de outils Selenium 4.X

### ISSUE THREAD

**Issue by InkUisitor** [cerberustesting/cerberus-core#2431]
Bonjour,
Après la fin de TestProject, j'ai décidé de porter mon dévolu sur Cerberus.
Après avoir mis à jour le docker-compose pour qu'il puisse fonctionner sur mon poste, j'ai tenté de réaliser quelques essais avec les dernières images Docker de Selenium en 4.X (mes dernières latest présentent une version 4.7).
Avec le changement d'API entre Selenium 3.141.59 et les versions 4.X, certaines portions de code de Cerberus ne sont plus fonctionnelles. Notamment la classe RobotServerService et sa méthode getIPOfNode qui ne peut plus fonctionner en l'état. L'exception de cette méthode empêche toute exécution de scénario en Selenium:latest alors qu'elle ne présente pas d'anomalie avec la Selenium:3.141.59.
Avez-vous pu faire des tentatives de migrations de Selenium plus poussées que celles que je tente ?
Je suis trop frais sur ce projet et n'étant pas du monde de Java, j'éprouve quelques difficultés à avancer correctement.
L'upgrade permettrait de fonctionner avec des versions de Chrome et de Firefox bien plus à jour.

**Comment by vertigo17** [comment]
Bonjour @InkUisitor , On a commencé quelques tests et le sujet est effectivement en cours.
Par contre on est egalement en train de travailler des images docker capable de prendre en charge des versions plus recente des navigateurs Chrome et Firefox avec un version 3.141.59 de Selenium. Ces images integreront le composant cerberus-robot-extension pour la prise en charge de la reconnaisance d'image et la gestion des usecase d'upload/download de fichiers.

**Comment by InkUisitor** [comment]
Bonjour @vertigo17. Merci pour les infos.
Je viens d'essayer une légère modification de la classe RobotServerService en supprimant l'usage de la méthode getIPOfNode (et en modifiant le traitement dans l'exception).
Voici ce que j'ai effectué : 
(RobotServerService.java:438)
`//getIPOfNode(tCExecution);`

(RobotServerService.java:483)
`mes.setDescription(mes.getDescription().replace("%URL%", "IpPort"));`
L'idéal serait de travailler avec le graphql de Selenium 4.X puisque l'API utilisée dans getIPOfNode n'existe plus. Mais pour le moment, je me suis accordé cette liberté. Ces modifications sont juste à des fins de test.

Et voici mon docker-compose sur Tomcat avec les dernières versions des nodes Chrome et Firefox + ajout de la ligne DATABASE_PASSWORD à cause d'une petite anomalie liée au mot de passe par défaut (qui est à "toto" au lieu d'être à "cerberus")

```
version: '2'
services:
  database:
    image: cerberustesting/cerberus-db-mysql:latest
    expose:
      - "3306"
    ports:
      - "13306:3306"
    volumes:
      - ./localdata/mysql-db:/var/lib/mysql
#      - /etc/localtime:/etc/localtime:ro
    restart: always
  cerberus:
    image: cerberustesting/cerberus-as-tomcat:latest
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=cerberus
    ports:
      - "8080:8080"
    volumes:
      - ./localdata/cerberusmedia:/opt/CerberusMedias/
#      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - database
    links:
      - database
  # Selenium-related services
  selenium-hub:
    image: selenium/hub:latest
    #image: selenium/hub:3.141.59
    expose:
      - "4444"
    ports:
      - "14444:4444"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    restart: always
  selenium-node-firefox:
    image: selenium/node-firefox:latest
    #image: selenium/node-firefox:3.141.59
    shm_size: 2gb
    environment:
      HUB_HOST: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    expose:
      - "5900"
    depends_on:
      - selenium-hub
    ports:
      - "15900:5900"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    restart: always
  selenium-node-chrome:
    image: selenium/node-chrome:latest
    #image: selenium/node-chrome:3.141.59
    shm_size: 2gb
    environment:
      HUB_HOST: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    expose:
      - "5900"
    depends_on:
      - selenium-hub
    ports:
      - "15901:5900"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    restart: always
```

Ces modifications m'ont permis de lancer un premier test avec des images Selenium toutes récentes (Chrome 108 et Firefox 106 + Node 4.7). Je vais pousser mes tests un peu plus loin vu que je n'ai aucun vrai test sur mon Cerberus pour le moment.
Est-ce que vous avez un groupe de discussion pour pouvoir partager vos travaux en cours ? Est-ce que vous avez des jeux de données de configuration de tests pour vérifier si mes modifications pourraient tenir la route ?
Bonne journée depuis Marcq-en-Baroeul ! ;)

**Comment by vertigo17** [comment]
Super.
On peut se partager une chaine sur le slack de Cerberus. Il me faudrait ton email pour t'inviter.
On a un environnement de test qa.cerberus-testing.com qui sert à faire la non reg sur Cerberus (il a automatiqueme la dernière version lié au dernier comit sur la master).
l'environnement prod.cerberus-testing.com lance lui les tests sur cet environnement de qa.
On peut imaginer que tu lances à partir de la prod.cerberus-testing.com la campagne sur ta machine si tu peux exposer ta version sur Internet.

**Comment by InkUisitor** [comment]
Ah chouette, je suis bien partant.
Voici mon adresse mail : jonathan.herbaut@gmail.com
J'ai pas mal de temps pour une étude de migration de solution de test et j'avoue que Cerberus part gagnant pour la suite de l'aventure dans ma boîte. Ce qui me laisse le temps par la même occasion de faire des petits ajustements si nécessaire.

**Comment by vertigo17** [comment]
Until compatibility is ready, you can use the following Dockerfile:
https://github.com/cerberustesting/cerberus-robot-extension/tree/master/docker

**Comment by InkUisitor** [comment]
Bonjour @vertigo17 ,
Je me permets de dépoussiérer ce thread. J'ai dernièrement refait une install d'un Cerberus et tout semble fonctionner avec l'image : cerberustesting/cerberus-as-tomcat:4.20. Ma grid est en 4.28 (latest), Chrome v142 (latest), FF v144 (latest)
La partie de mon docker-compose actuelle est la suivante et tout est OK en l'état :
```
version: '2'
services:
  database:
    image: cerberustesting/cerberus-db-mysql:latest
    platform: linux/amd64
    expose:
      - "3306"
    ports:
      - "13306:3306"
    volumes:
      - /srv/Cerberus-Docker/localdata/mysql-db:/var/lib/mysql
    restart: always
  cerberus:
    image: cerberustesting/cerberus-as-tomcat:4.20
    platform: linux/amd64
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
    ports:
      - "80:8080"
    volumes:
      - /srv/Cerberus-Docker/localdata/cerberusmedia:/opt/CerberusMedias/
    restart: always
    depends_on:
      - database
    links:
      - database
  selenium-hub:
    container_name: selenium-hub-4
    image: selenium/hub:latest
    platform: linux/amd64
    ports:
      - "4444:4444"
    restart: always
  selenium-node-firefox:
    deploy:
      mode: replicated
      replicas: 1
    image: selenium/node-firefox:latest
    platform: linux/amd64
    shm_size: 2gb
    environment:
      HUB_HOST: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    depends_on:
      - selenium-hub
    restart: always
  selenium-node-chrome:
    deploy:
      mode: replicated
      replicas: 1
    image: selenium/node-chrome:latest
    platform: linux/amd64
    shm_size: 2gb
    environment:
      HUB_HOST: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
    depends_on:
      - selenium-hub
    restart: always
```
Je pense que vous pourriez peut-être fermer ce ticket
